[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
extra_scripts = pre:scripts/load_env.py
lib_deps =
    makuna/Rtc
    bblanchon/ArduinoJson
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ILI9341 @ ^1.6.0
    adafruit/Adafruit BusIO @ ^1.16.1
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
monitor_speed = 115200
upload_speed = 921600
