[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
extra_scripts = pre:scripts/load_env.py
lib_deps =
    olikraus/U8g2
    makuna/Rtc
    bblanchon/ArduinoJson
monitor_speed = 115200
upload_speed = 921600
